class Data:
    PEP="pep"
    PEP_ALARM="pep_alarm"
    FIO2="fio2"
    VT="vt"
    FR="fr"
    FLOW="flow"
    TPLAT="tplat"
    VTE="vte"
    VTE_ALARM="vte_alarm"
    VMIN="vmin"
    PPLAT="pplat"
    PCRETE="pcrete"
    PCRETE_ALARM="pcrete_alarm"
    PMAX="pmax"
    PMIN="pmin"
    VM="VM"
